name: 'Appcircle Enterprise App Store'
author: 'appcircleio'
description: 'Efficiently publish your apps to Appcircle Enterprise App Store.'

branding:
  icon: 'activity'
  color: 'orange'

inputs:
  personalAPIToken:
    description:
      'Provide Appcircle Personal API Token to authenticate Appcircle services.'
    required: true
  appPath:
    description:
      'Specify the path to your application file. For iOS, this can be a .ipa or
      .xcarchive file path. For Android, specify the .apk or .appbundle file
      path'
    required: true
  summary:
    description: 'Summary Notes For Publishment'
    required: true
  releaseNotes:
    description: 'Release Notes For Publishment'
    required: true
  publishType:
    description: 'Publish Type' # 0: None, 1: Beta, 2: Live
    required: false
    default: '0'
runs:
  using: 'node20'
  main: 'dist/index.js'
