name: 'Appcircle Enterprise Store'
author: 'appcircleio'
description: 'Efficiently publish your apps to Appcircle Enterprise Store.'

branding:
  icon: 'icon.png'
  color: 'blue'

inputs:
  accessToken:
    description:
      'Provide the Appcircle access token to authenticate connections to
      Appcircle services. This token allows your Azure DevOps pipeline to
      interact with Appcircle for distributing applications'
    required: true
  entProfileId:
    description:
      'Provide the Appcircle Enterprise App Store Mobile Profile ID to specify
      the profile to be used for the publishment. This ID can be found in the
      Enterprise App Store Mobile module dashboard.'
    required: true
  appPath:
    description:
      'Specify the path to your application file. For iOS, this can be a .ipa or
      .xcarchive file path. For Android, specify the .apk or .appbundle file
      path'
    required: true
  summary:
    description: 'Summary Notes For Publishment'
    required: true
  releaseNotes:
    description: 'Release Notes For Publishment'
    required: true
  publishType:
    description: 'Publish Type' # 0: None, 1: Beta, 2: Live
    required: false
    default: '0'
runs:
  using: 'node20'
  main: 'dist/index.js'
