on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Appcircle-Testing-Distribution-Action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Local Action
        id: testing-distribution
        uses: appcircleio/appcircle-testing-distribution-githubaction@v0.0.1
        with:
          accessToken: ${{ secrets.AC_ACCESS_TOKEN }}
          entProfileId: ${{ secrets.AC_PROFILE_ID }}
          appPath: ./Appcircle.ipa
          summary: Github Action Summary
          releaseNotes: Github Action Release Notes
          publishType: '0'
